### ISSUE TITLE
Pause when not watching channels are being reset

### ISSUE THREAD

**Issue by gonzo90017** [Steveb1968/script.pseudotv#5]
I have reset channels set to "Never" in PseudoTV's settings.. But for some reason it always resets the channel that I have set as "Pause when not watching" and "Force Resume Mode". All other channels are not reset except this one. It works as intended a couple of times. But when I come back to it. I see PseudoTV resetting that one channel. 
Here is my Log:
https://paste.ubuntu.com/23709945/

And my settings:
[settings.zip](https://github.com/Steveb1968/script.pseudotv/files/678321/settings.zip)

**Comment by Steveb1968** [comment]
Not sure what your trying to do but "Pause when not watching" and "Force Resume Mode" basically cancel each other out!!
Maybe try, select a channel type" tvshow" >then select the show> then select "sort method episode".
Then go to advanced rules and set "Pause when not watching".
Hope that helps!

**Comment by Steveb1968** [comment]
PS: Thanks for the log & user files, will give it thought when I get back off holiday's.
Cheers.

**Comment by Steveb1968** [comment]
Yes, you have to careful with the order of Advanced channel rules, especially if the rule is performing a action on the playlist.
e.g. The "Even Show Distribution" rule will do nothing if you've already "Interleaved another channel" with a previous rule.
Just use some basic logic on how you process and display the list.
Not sure you need the "Force Resume Mode" if the playlist is "Pause when not Watching" but I don't know all the settings for the channel. :)

**Comment by gonzo90017** [comment]
I upgraded to the lastest version of kodi v17.

Channel 1: **Pause When not watching** only
Channel only pauses when inside of PseudoTV. Once you exit PseudoTV, then launch it again. Channel goes back to the beginning of the playlist.

Channel 2: **Force Resume** only
This works the first few times in that it saves your position when you exit PseudoTV. However, once you launch PseudoTV again and switch channels. The channel keeps playing in Real Time. After a few times of entering and exiting PseudoTV it goes back to the beginning of the list like the other channels.

Channel 3: **Pause When not watching** and **Force Resume**
This combination worked perfectly in v14.2. In v17.0 it behaves like in my first post:
(I also tried it with Force Resume as the first rule then Pause when not watching. Did not work either)

https://paste.ubuntu.com/23736670/
[Settings.zip](https://github.com/Steveb1968/script.pseudotv/files/683708/Settings.zip)

**Comment by Steveb1968** [comment]
There are no errors in the log file.

Set **reset channels** to **Automatic** (this wont effect the resume/paused channels just needed for the real-time). It just determines what to do when you get to the end of a playlist. If set to never you will watch the same things (playlist limit) over and over until you do a manual **force channel reset**.
Also not sure why you have background updating turned **off**, leave that at default **Minimal use** its needed to keep channels up to date (whether paused/resume or real-time).

Adv. Rule 1 **Force Resume**
Adv. Rule 2 **Pause When not watching**
Works as expected here Kodi v17 on both Win10 and Libreelec.
Tested on multi-pal channels.

**Comment by mwkurt** [comment]
If I may interject an observation in this thread....I notice the same thing happening and could never figure it out. My wife actually came across the cure to the problem. Basically, my "Pause when not watching/Force resume" channels would reset themselves whenever I started PTV. What it had to do with was how we exited PTV. I always used the "Back" button that would then ask if I "really wanted to quit PTV". I'd select yes, then PTV would save the settings and exit. When I restarted PTV, my channels would reset. My wife was just using the "Stop" button. This didn't ask if she wanted to quit but would also save the settings and exit PTV. For whatever reason they save the settings differently. The "Back' button doesn't save the resume/pause rules while the "Stop" button will. This is using a standard remote. Give the two a try and see if there is a difference for you guys.
As an aside, Using earlier versions of the original PTV worked as it should using the "Back" button.
Mark

**Comment by Steveb1968** [comment]
Interesting, I always use the stop button to exit so I've never come across this issue. I will have a closer look. I know in the settings the back button on the remote doesn't save it acts as cancel, you have to use the exit on the remote or the ok button in the gui. I added a cancel button to some of the settings dialogs maybe that has something to do with it. Thanks for the heads up.
Cheers.

**Comment by Steveb1968** [comment]
Could you try the test fix I just pushed too see if that helps. If it solves the problem at least I will know which area of code I need to look at.
Cheers.

**Comment by gonzo90017** [comment]
I just tested the fix. But at least for me the issue remains the same. I watched the channel then exited PseudoTV by using the back button then clicking exit. I launch PseudoTV again and playback goes to the start. I also tried it using the stop button but got the same result.

https://paste.ubuntu.com/23750007/
[settings.zip](https://github.com/Steveb1968/script.pseudotv/files/688838/settings.zip)

**Comment by Steveb1968** [comment]
This your settings2.xml

<settings>
    <setting id="Version" value="2.4.4" />
    <setting id="Channel_1_type" value="6" />
    <setting id="Channel_1_1" value="Batman: The Brave and the Bold" />
    <setting id="Channel_2_type" value="9999" />
    <setting id="Channel_2_1" value="" />
    <setting id="Channel_3_type" value="9999" />
    <setting id="Channel_3_1" value="" />
    <setting id="Channel_4_type" value="9999" />
    <setting id="Channel_4_1" value="" />
    <setting id="Channel_5_type" value="9999" />
    <setting id="Channel_5_1" value="" />
    <setting id="LastResetTime" value="1483666005" />
    <setting id="Channel_1_time" value="423" />
    <setting id="Channel_2_time" value="0" />
    <setting id="Channel_3_time" value="0" />
    <setting id="Channel_4_time" value="184526" />
    <setting id="Channel_5_time" value="184526" />
    <setting id="LastExitTime" value="1483666429" />
    <setting id="Channel_1_changed" value="False" />
    <setting id="Channel_2_changed" value="True" />
    <setting id="Channel_3_changed" value="True" />
    <setting id="Channel_4_changed" value="True" />
    <setting id="Channel_5_changed" value="True" />
    <setting id="Channel_5_2" value="" />
    <setting id="Channel_4_2" value="" />
    <setting id="Channel_2_2" value="" />
    <setting id="Channel_3_2" value="" />
    <setting id="Channel_1_2" value="4" />
    <setting id="Channel_1_rulecount" value="1" />
    <setting id="Channel_1_rule_1_id" value="8" />
    <setting id="Channel_1_rule_2_id" value="12" />
    <setting id="Channel_2_rulecount" value="1" />
    <setting id="Channel_2_rule_1_id" value="9" />
    <setting id="Channel_3_rulecount" value="2" />
    <setting id="Channel_3_rule_1_id" value="9" />
    <setting id="Channel_3_rule_2_id" value="8" />
</settings>

Channel 1 is what you tested with.

"Channel_1_type" value="6" = TvShow
"Channel_1_1" value="Batman: The Brave and the Bold" = Batman: The Brave and the Bold
"Channel_1_2" value="4" = Sort method (episode) selected for tvshow channel
"Channel_1_rulecount" value="1" = Number of Adv. rules (1)
"Channel_1_rule_1_id" value="8" = Pause when not watching

You have another adv. rule "Channel_1_rule_2_id" value="12" = "Play TV Shows In Order" which isn't needed because of "Channel_1_2" value="4" = Sort method (episode) selected for tvshow channel.
But your Channel_1_rulecount" value="1" so I guess you removed that (good :)).

For this type of channel your missing 1 Adv. rule to make it work..
"Channel_1_rule_2_id" value="9" = Force resume mode

You have that rule for channels 2 & 3 but they are not in use.

Tested here and its working with back and stop commands.

**Comment by Steveb1968** [comment]
@mwkurt & gonzo90017. Thanks for alerting me to the "on back" bug! I haven't got much spare time (except for this time of year), Work..work..work.
I just try to keep what I like going, going as best I can anyway, so some areas I don't use will suffer.... ;).
Always good to get some feed back.
Cheers.

**Comment by mwkurt** [comment]
The "on back" bug? There is a bug using the "back" button?

**Comment by gonzo90017** [comment]
After a full day of testing it seems like everything is working fine in v17. However I had to downgrade all the way back to 15.2 because of some coming out of standby issues (v17). And some focus issues (v16).

These issues are present in both v16 and v15.2. 
Channel 7: 
1. Pause when not watching
2. Force Resume Mode

Pause when not watching is not working. You exit PseudoTV or even change the channel and come back to channel 7, and playback starts at the beginning of the episode. Not where you left off.

All channels except channel 7 are set to Real Time. However whenever you change the channel. Playback starts from the beginning of the episode. Even if the guide shows that a movie is halfway through or towards the end.

The above issues were not present in v17. I tested these for about a day looking out for these issues. I copied the setting2.xml file so all channels are exactly the same.

[Settings.zip](https://github.com/Steveb1968/script.pseudotv/files/694506/Settings.zip)
[Kodi Log File.zip](https://github.com/Steveb1968/script.pseudotv/files/694507/Kodi.Log.File.zip)

**Comment by Steveb1968** [comment]
Sorry for the late reply! I've been chasing this bug for over two years, Thanks FernetMenta! :)
Go for v17..

**Comment by mwkurt** [comment]
Are you saying we have to upgrade to Kodi V17 to have PseudoTV work correctly?

**Comment by gonzo90017** [comment]
I think he was just referring to the issues I mentioned in my last post. 

I have one more issue that is present in 14.2. Playback always starts from the beginning of the movie when using .m2ts files (bluray rips). I just thought I'd mention these issues in case someone is using an older Kodi version like me. 

I'll upgrade Kodi to v17 when it reaches final. Hopefully they fix the waking up from sleep issues.

**Comment by Steveb1968** [comment]
@ mwkurt. The updates to the video player for v17 make Krypton the best option for smooth channel changes and all round speed and performance. But you can do what you like! Eventually things must move forward and older versions of XBMC/Kodi will not be supported! As of now v15+ should work but as stated v17 is recommended.

**Comment by mwkurt** [comment]
Stevb,

I have upgraded Kodi 17.3 and am having a problem with the rules "Pause when not watching" and Force resume mode". They do not appear to be working. I am using Kodi and PTV on a Shield TV android unit. Do not know if the operating system matters, but was hoping that somehow, someway, I could get this working. I am using PTV ver. 2.4.4. Would appreciate any help possible. Thanks!

**Comment by Steveb1968** [comment]
@ mwkurt,
Just pushed a bit of test code to see if it fixes the problem. If not I'll have to dig deeper. ;)
Could of swore I already had a look at this, must of got side tracked.
I've only got Win10 and LibreELEC to test on but works ok for me.

This code needs a good cleanup at some point, but I'm time poor at the moment.

**Comment by mwkurt** [comment]
Will give a try later today and let you know. I was using a smart playlist
with 5 or 6 tv shows set to episodes. The only 2 rules I had were "Pause"
and "resume" and every time I stop and restart PTV, the channel reloads. It
is the only channel I am currently testing. I can't figure it out.

Thanks for trying!
Mark

**Comment by Steveb1968** [comment]
No probs, give it a go.
Not sure you need "pause when not watching" if you have "force resume" on the same channel.
"Paused" only kick's in if you switch to another channel and "resume" works from a restart/channel switch... or it should. :) Everyone to there own though, you must have a reason. :)
That should still work though, hopefully, just haven't tried it. :)

**Comment by mwkurt** [comment]
I'll give it a try, both ways. Back when PTV was first developed, I
remember that Jason said to use both channel rules, so that is what I did.
I am very open to doing it whatever way works. :-)

Thanks,

Mark

**Comment by Steveb1968** [comment]
Yea man, there are some creative channels you can create.. I hope it helps.
If not just lest me know.
I've got some new ideas for the rules section, just got to get around to coding them. :)

**Comment by mwkurt** [comment]
Steve,

Looks as if the update you made works as my channels now pause and resume.
THANK YOU SO MUCH!!!!!!!!!

One thing, I tried downloading the whole PTV package and it wouldn't
install. I had to just download the stuff for the "Addon" folder. I will
let you know if anything else should come up.

Thank you,
Mark


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
